from graphviz import Digraph

# 创建 Digraph 对象
dot = Digraph(comment='智能垃圾分类回收系统技术路线流程图', format='png')

# 定义节点
dot.node('A', '数据采集与预处理')
dot.node('B', '模型构建与优化')
dot.node('C', '硬件设计与搭建')
dot.node('D', '实验验证与分析')
dot.node('A1', '图像采集')
dot.node('A2', '数据增强')
dot.node('A3', '数据标注')
dot.node('B1', '选择基础模型')
dot.node('B2', '引入注意力机制')
dot.node('B3', '多边形点数优化')
dot.node('B4', '交叉验证')
dot.node('C1', '总体方案设计')
dot.node('C2', '机械结构设计')
dot.node('C3', '硬件结构与环境搭建')
dot.node('D1', '模型训练与评估')
dot.node('D2', '抓取实验')
dot.node('C21', '抓取装置设计')
dot.node('C22', '分类装置设计')
dot.node('C23', '压缩装置设计')
dot.node('C24', '满载装置设计')
dot.node('C31', '硬件结构设计')
dot.node('C32', '系统运行环境搭建')
dot.node('B11', '选择 YOLO V5s 作为基础模型')
dot.node('A11', '使用双目摄像头在不同光照、背景环境和姿态下采集垃圾图像数据')
dot.node('A21', '收集 2000 余张垃圾图像并采用数据增强技术扩充数据集')
dot.node('A31', '使用 LabelImg 软件对采集的垃圾图像进行处理')
dot.node('B21', '引入 CBAM 注意力机制模块')
dot.node('B31', '设定角度阈值和距离阈值优化多边形点数')
dot.node('B41', '采用交叉验证的方法优化模型')
dot.node('C11', '设计智能垃圾分类回收装置并展示工作流程图')
dot.node('C211', '设计双轴机械臂和机械爪')
dot.node('C221', '选用传送带作为垃圾分拣系统的核心组件')
dot.node('C231', '选择曲柄连杆装置压缩方案')
dot.node('C241', '利用光电传感器实现对垃圾桶内垃圾量的实时监测')
dot.node('C311', '使用 MKS_Gen_L 驱动板和 Jetson Nano 控制板等进行硬件结构设计')
dot.node('C321', '在 Win11 系统平台上进行系统运行环境搭建')
dot.node('D11', '使用优化后的 YOLO V5s 模型对垃圾图像数据集进行训练')
dot.node('D21', '搭建垃圾分类抓取实验系统并验证系统有效性')

# 定义边
dot.edges(['AB', 'BC', 'CD'])
dot.edge('A', 'A1')
dot.edge('A', 'A2')
dot.edge('A', 'A3')
dot.edge('B', 'B1')
dot.edge('B', 'B2')
dot.edge('B', 'B3')
dot.edge('B', 'B4')
dot.edge('C', 'C1')
dot.edge('C', 'C2')
dot.edge('C', 'C3')
dot.edge('D', 'D1')
dot.edge('D', 'D2')
dot.edge('A1', 'A11')
dot.edge('A2', 'A21')
dot.edge('A3', 'A31')
dot.edge('B1', 'B11')
dot.edge('B2', 'B21')
dot.edge('B3', 'B31')
dot.edge('B4', 'B41')
dot.edge('C1', 'C11')
dot.edge('C2', 'C21')
dot.edge('C2', 'C22')
dot.edge('C2', 'C23')
dot.edge('C2', 'C24')
dot.edge('C3', 'C31')
dot.edge('C3', 'C32')
dot.edge('C21', 'C211')
dot.edge('C22', 'C221')
dot.edge('C23', 'C231')
dot.edge('C24', 'C241')
dot.edge('C31', 'C311')
dot.edge('C32', 'C321')
dot.edge('D1', 'D11')
dot.edge('D2', 'D21')

# 生成流程图
dot.render('智能垃圾分类回收系统技术路线流程图', view=True)